### ISSUE TITLE
Must do a pull before run to update to latest version 

### ISSUE THREAD

**Issue by jonakarl** [MONROE-PROJECT/Utilities#2]
Before each run a pull should be preformed to update the image to the latest version. 

eg. 
docker pull $URL_PING
@
https://github.com/MONROE-PROJECT/Utilities/edit/master/monroe-experiments/usr/bin/monroe-experiments#L49
https://github.com/MONROE-PROJECT/Utilities/edit/master/monroe-experiments/usr/bin/monroe-experiments#L54

**Comment by relet** [comment]
With the experiment containers possibly running for weeks, I think we should rather put the update mechanism into ansible. This script only executes docker if the container is not already running.

Do you agree?

**Comment by jonakarl** [comment]
Then I believe we should do it both in ansible and in this script. The pull is very fast (if nothing changed) and I believe it is important that we ensure we are on the latest version at all times.
